version: '3.8'

services:
  app:
    build:
      context: itemmanager
      dockerfile: Dockerfile
    image: itemmanager:latest
    restart: on-failure
    ports:
      - 3000:8080
    stdin_open: true
    tty: true